# Generated by Django 4.2.7 on 2025-09-16 06:59

from django.db import migrations, models
import media_handler.models


class Migration(migrations.Migration):

    dependencies = [
        ('media_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=media_handler.models.media_upload_path),
        ),
        migrations.AlterField(
            model_name='media',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='storage_path',
            field=models.CharField(blank=True, editable=False, max_length=500, null=True),
        ),
    ]
